### ISSUE TITLE
Поддержать правила ЕМА-2016

### ISSUE THREAD

**Issue by ctizen** [Furiten/riichi-statboard#18]
- Поддержать двойные и тройные роны 🆗 
- Казоэ - санбайман, а не якуман ❗ 
- Чомбо - всегда только -20 очков; выплаты не производятся - поправить проверку по очкам.🆗 
- Поддержать правильное получение ричей при двойных и тройных ронах; также поддержать правильное получение хонбы в этих случаях🆗 
- В конце игры все риичи на кону уходят победителю; если победителей более одного - делятся поровну - поддержать.🆗 
- Ума 15/5, но нужно поддержать расчет умы по среднему в случае равенства очков (например по +10 каждому если 1и 2 места набрали ровное число очков).❗

**Comment by heilage-nsk** [comment]
Пока пилим отдельной веткой, чтобы не парить мозг.
На будущее надо понять, как лучше сделать настройки. Потенциальный отказ от ЕМА - не повод не поддержать правила.

**Comment by heilage-nsk** [comment]
Проблема с множественным роном в том, что надо будет городить отдельную обработку, т.к. надо учитывать выигрыш дилера независимо от того, каким номером зарегистрирована его победа.
