### ISSUE TITLE
Разделить систему на client-side и server-side

### ISSUE THREAD

**Issue by ctizen** [Furiten/riichi-statboard#33]
Цель: единый бэкенд для веб и (потенциально могущей появиться) мобилки.
Чисто бэкендную часть надо сделать в виде некоторого api.

**Comment by Nihisil** [comment]
Для бэкенда предлагаю сделать обычный RPC (REST слишком чистый и на нашу задачу не ложится) который будет пуляться JSON'ом.

Про фронт у тебя какие идеи? Angular2 + React?

**Comment by heilage-nsk** [comment]
Определенно обычный JSON-RPC. Никаких рестов и графкюэлов.
На фронт - не знаю пока. Ангуляр осваивать никакого желания, реакт - вполне вероятно, да. Маленькое победоносное SPA это то что нужно. Тем более что SEO и как следствие серверный рендеринг тут в общем-то и не требуются.

**Comment by heilage-nsk** [comment]
Кстати, если понадобится сео, возможно гораздо проще будет нагородить простейшее клиентское приложение без всяких джаваскриптов, которое будет ходить за данными в апи и отображать как надо :) При этом без всяких там красивых графиков и прочего чисто клиентского говна. За графиками - велком в полную SPA-версию. Надо только кросс-линки настроить.

**Comment by Nihisil** [comment]
Для бэкенеда я бы взял какой-нибудь простой фреймворк который умеет в роутинг, парсинг аттрибутов запроса и отображение ответа, чтоб самим это все не писать. Хотя это не критично.
