### ISSUE TITLE
Сквозной рейтинг игрока

### ISSUE THREAD

**Issue by Nihisil** [Furiten/riichi-statboard#34]
[Требует обсуждения]

Сейчас для новый мероприятий система устанавливается каждый раз заново и не имеет связей с предыдущими записями. Думаю было бы хорошо уметь поддерживать "мульти-турнирность" (хз как это назвать).

Добавляем в систему возможность регистрировать такие сущности как турнир или клубный рейтинг. Например кто-то из Якутска решил использовать систему, но навыков и возможностей установить ее на свой сервер нет, поэтому он просто регистрирует новую сущность и получает рейтинг для своих игроков. Так же они поступают когда хотят сделать свой небольшой городской турнир.

Игрок участвующий в клубном рейтинге и онлайн турнире будет иметь общую статистику по всем суммарным ханчанам и отдельную статистику по каждой отдельной сущности.

Юзер будет уникальный, но может иметь несколько привязанных к себе ников - Vovka11!! (в онлайн турнире) и Vladimir_Ivanov (в оффлайн турнире) и т.п.

Из плюсов получаем более консистентные данные и возможность пользоваться (проводить турниры, вести клубный рейтинг) системой для не технических людей.

Из минусов получаем головняк с отождествлением юзера и ника под которым он играл на турнирах (частично снимается правильными вопросами при организации турнира, но добавляет головняков с организации турнира).

В общем хочу услышать, что ты думаешь об этом всем.

**Comment by heilage-nsk** [comment]
Да, я тоже об этом думал. К тому же это прекрасно вписывается в долгосрочные цели нашего клуба и в цели общего риичи-движения по стране. Но кажется, в первую очередь надо сделать #33, мне кажется что после него все вышеописанное будет сделать проще, поскольку концепция api предполагает очень полное покрытие системы юнит- и интеграционными тестами. К тому же тогда будет некая возможность запилить рейтинг к себе на сайт локального клуба, т.к. предполагается api для доступа к статистике.

**Comment by heilage-nsk** [comment]
И да, разделение может привлечь дополнительные силы в лице разработчиков отдельно-фронтенда и отдельно-бэкенда, не все любят пхп :)

**Comment by Nihisil** [comment]
Мысли о том, что кто-то будет пилить свой клиент на основе API это еще та утопия) Но с мыслью о разделении фронта и бэка полностью согласен, будет полезно.
