### ISSUE TITLE
Ускорение скорости ввода оффлайн логов

### ISSUE THREAD

**Issue by Nihisil** [Furiten/riichi-statboard#38]
Первое что пришло в голову, это добавление автокомплита. Он будет содержать в себе всех игроков и все возможные яку.

Например ты начинаешь вводить sa - автокомплит предлагает выбрать sanshoku.

Сам я логи не забивал, но думаю это должно немного, но помочь. Что думаешь?

Один из возможных кандидатов: http://yuku-t.com/jquery-textcomplete/

**Comment by heilage-nsk** [comment]
Ускорение определенно нужно, но я думал его добиваться другим путем - сгрузив максимум на игроков и одновременно разгрузив их от рукописной работы. Как? Сделав мобильное приложение с ясным и понятным интерфейсом, которое могло бы ходить в апи системы и добавлять игры. Пока это только задумка, но именно из нее родилась потребность разделения системы на апи и фронтенд.

**Comment by Nihisil** [comment]
Да, про такое приложение(мб мобильную версию?) я тоже думал. Только сделать ясный и понятный интерфейс в таком деле будет не так уж и просто, но что-нибудь да придумаем. 

Тут еще надо подумать, что делать когда в конце ханчана не сойдется то что в приложение позабивали с теми очками которые на самом деле у людей остались.

**Comment by heilage-nsk** [comment]
Задумка в том, чтобы приложение было единственным источником правды. Если будет приложение - очковые палки будут не нужны. Это конечно довольно радикально, но думаю подход вполне может себя оправдать.

**Comment by Nihisil** [comment]
Без палок не лампово))

**Comment by Nihisil** [comment]
Но это я так, не серьезно. С идеей все делать через приложение я согласен

**Comment by ctizen** [comment]
Кажется это можно закрывать. Все равно уже работы в разгаре и направлены именно на это.
