### ISSUE TITLE
Учитывать все собранные руки в номинации "Лучшая рука"

### ISSUE THREAD

**Issue by heilage-nsk** [Furiten/riichi-statboard#4]
Пример:

В номинации:
Лучшая рука собрана игроком heilage - 6 хан

Полный лог игры:
....
東2: heilage - Чиницу, дора 1 (цумо), 6 хан
....
南3: suddha28 - Пин-фу, Риичи, дора 4 (Полуось), 6 хан

Нужно, чтобы обе руки учитывались в номинации, сейчас учитывается только первая из равных.

**Comment by Nihisil** [comment]
Сделаю сегодня или завтра как первый таск
